apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bloaty-mcbloatface
  namespace: udacity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bloaty-mcbloatface
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 100Mi